language: node_js
sudo: false

node_js:
  - "6"

before_script:
  - npm i -g yarn --cache-min 999999999
  - yarn config set cache-folder yarn-cache
  - yarn
  - rvm install 2.2.2
  - gem install scss_lint
  - export DISPLAY=:99
  - npm run post-install

cache:
  paths:
    - yarn-cache/

script:
- npm run lint
- npm run scss-lint
- /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
- npm run test
- npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
